version: "3"

services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=api-rest-node
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "8888:8888"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=api-rest-node
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
